# Generated by Django 6.0.2 on 2026-02-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название новости')),
                ('desc', models.TextField(verbose_name='Ознакомительное описание')),
                ('content', models.TextField(verbose_name='Html код для страницы')),
                ('news_views', models.IntegerField(default=0, verbose_name='Количество просмотров новости')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ManyToManyField(to='api.category', verbose_name='Категория новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
