# Generated by Django 6.0.2 on 2026-02-27 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название аудио')),
                ('audio', models.FileField(upload_to='allAudio', verbose_name='Аудио')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Аудио',
                'verbose_name_plural': 'Аудио',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название категории')),
                ('slug', models.SlugField(default='', verbose_name='Slug название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название изображение')),
                ('image', models.ImageField(upload_to='allImages', verbose_name='Изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название рилса')),
                ('image', models.ImageField(upload_to='reels', verbose_name='Превью рилса')),
                ('content', models.TextField(verbose_name='Втройка рилса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки рилса на сайт')),
            ],
            options={
                'verbose_name': 'Рилс',
                'verbose_name_plural': 'Рилс',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название видио')),
                ('image', models.ImageField(upload_to='reels', verbose_name='Превью видио')),
                ('link', models.CharField(max_length=300, verbose_name='Сслыка на ютуб видео')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки видио на сайт')),
            ],
            options={
                'verbose_name': 'Ютуб видео',
                'verbose_name_plural': 'Ютуб видео',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название подкатегории')),
                ('slug', models.SlugField(default='', verbose_name='Slug название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='api.category', verbose_name='Категория подкатегории')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название новости')),
                ('short_title', models.CharField(max_length=300, verbose_name='Краткое название новости')),
                ('desc', models.TextField(verbose_name='Ознакомительное описание')),
                ('content', models.TextField(verbose_name='Html код для страницы')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров новости')),
                ('preview', models.ImageField(upload_to='news/', verbose_name='Превью изображение')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='news/main/', verbose_name='Главное изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.category', verbose_name='Категория новости')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.subcategory', verbose_name='Подкатегория новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
