# Generated by Django 6.0.2 on 2026-02-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(upload_to='news/previews/', verbose_name='Превью изображение'),
        ),
    ]
