# Generated by Django 6.0.2 on 2026-02-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='preview',
            field=models.CharField(default='', verbose_name='Превью изображение'),
        ),
    ]
