# Generated by Django 6.0.2 on 2026-02-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_news_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.CharField(verbose_name='Превью изображение'),
        ),
    ]
