# Generated by Django 6.0.2 on 2026-02-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_news_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(upload_to='news/main/', verbose_name='Главное изображение'),
        ),
    ]
