# Generated by Django 6.0.2 on 2026-02-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('desc', models.TextField(verbose_name='Ознакомительное описание')),
                ('content', models.TextField(verbose_name='Html код для страницы')),
                ('article_views', models.IntegerField(default=0, verbose_name='Количество просмотров статьи')),
                ('preview', models.CharField(verbose_name='Превью изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('category', models.ManyToManyField(to='api.category', verbose_name='Категория статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
