# Generated by Django 6.0.2 on 2026-02-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_title',
            field=models.CharField(default='', max_length=50, verbose_name='Краткое название статьи'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_title',
            field=models.CharField(default='', max_length=50, verbose_name='Краткое название новости'),
        ),
    ]
