# Generated by Django 6.0.2 on 2026-02-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_article_short_title_news_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview',
            field=models.ImageField(upload_to='articles/', verbose_name='Превью изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.ImageField(upload_to='news/', verbose_name='Превью изображение'),
        ),
    ]
