# Generated by Django 6.0.2 on 2026-02-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название альбома')),
                ('short_title', models.CharField(default='', max_length=50, verbose_name='Краткое название альбома')),
                ('desc', models.TextField(verbose_name='Ознакомительное описание')),
                ('content', models.TextField(verbose_name='Html код для страницы')),
                ('album_views', models.IntegerField(default=0, verbose_name='Количество просмотров альбома')),
                ('preview', models.ImageField(upload_to='album/', verbose_name='Превью изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('category', models.ManyToManyField(to='api.category', verbose_name='Категория альбома')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
    ]
