# Generated by Django 6.0.2 on 2026-02-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to='allAudio', verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='allImages', verbose_name='Изображения'),
        ),
    ]
