# Generated by Django 6.0.2 on 2026-02-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_audio_audio_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_views',
            new_name='views',
        ),
    ]
