# Generated by Django 6.0.2 on 2026-02-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_news_views_news_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_views',
            new_name='views',
        ),
    ]
