# Generated by Django 6.0.2 on 2026-02-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_article_views_article_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_views',
            new_name='views',
        ),
    ]
