# Generated by Django 6.0.2 on 2026-02-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_album_views_album_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='short_title',
            field=models.CharField(max_length=50, verbose_name='Краткое название альбома'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_title',
            field=models.CharField(max_length=50, verbose_name='Краткое название статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_title',
            field=models.CharField(max_length=50, verbose_name='Краткое название новости'),
        ),
    ]
