# Generated by Django 6.0.2 on 2026-02-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.subcategory', verbose_name='Подкатегория новости'),
        ),
        migrations.AddField(
            model_name='article',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.subcategory', verbose_name='Подкатегория новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.subcategory', verbose_name='Подкатегория новости'),
        ),
    ]
