# Generated by Django 6.0.2 on 2026-02-17 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_album_subcategory_article_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug название'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug название'),
        ),
        migrations.AlterField(
            model_name='album',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subcategory', verbose_name='Подкатегория новости'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subcategory', verbose_name='Подкатегория новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subcategory', verbose_name='Подкатегория новости'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(verbose_name='Название подкатегории'),
        ),
    ]
