# Generated by Django 6.0.2 on 2026-02-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_category_slug_subcategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.subcategory', verbose_name='Подкатегория новости'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.subcategory', verbose_name='Подкатегория новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.subcategory', verbose_name='Подкатегория новости'),
        ),
    ]
