# Generated by Django 6.0.2 on 2026-02-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_album_subcategory_alter_article_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategries', to='api.category', verbose_name='Категория подкатегории'),
        ),
    ]
