# Generated by Django 6.0.2 on 2026-02-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название рилса')),
                ('image', models.ImageField(upload_to='reels', verbose_name='Превью рилса')),
                ('content', models.TextField(verbose_name='Втройка рилса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки рилса на сайт')),
            ],
            options={
                'verbose_name': 'Рилс',
                'verbose_name_plural': 'Рилс',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
