# Generated by Django 6.0.2 on 2026-02-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_reel_remove_article_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название рилса')),
                ('image', models.ImageField(upload_to='reels', verbose_name='Превью рилса')),
                ('link', models.CharField(max_length=200, verbose_name='Ссслыка на ютуб видео')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки рилса на сайт')),
            ],
            options={
                'verbose_name': 'Ютуб видео',
                'verbose_name_plural': 'Ютуб видео',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='reel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рилс', 'verbose_name_plural': 'Рилс'},
        ),
    ]
