# Generated by Django 6.0.2 on 2026-02-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_youtubevideo_alter_reel_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YouTubeVideo',
            new_name='YouTubeVids',
        ),
    ]
